name: Bug report
description: Create a report to help us fix a bug
title: "issue: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below as completely as possible.

  - type: input
    id: reproduction
    attributes:
      label: Reproduction Case
      description: Provide a minimal reproduction example (e.g. a CodeSandbox link)
      placeholder: https://codesandbox.io/s/your-repro-example
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Runtime (Node.js, Bun, Deno, etc) and version."
      placeholder: e.g., Node.js 18.12.1, Bun v0.6.0
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected result
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe the observed result or error
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information, logs, or screenshots
      placeholder: Paste logs or add links here
