name: Feature request
description: Suggest an idea for this project
title: "feature: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem_description
    attributes:
      label: Problem Description
      description: What problem does this feature solve or what need does it address?
      placeholder: Describe the issue or need in detail
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution or approach
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives or workarounds?
      placeholder: List any other options or solutions you thought of

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature for you?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information, links, or examples to help understand this feature request
      placeholder: Add context here
